### ISSUE TITLE
InternalError: (0, u'Connection is already in use.')

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#683]
1 occurrence 10/25
```
Handler:	sjfnw/wsgi.py
URL:	https://sjf-nw.appspot.com/admin/fund/givingproject/add/
Stacktrace:	
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/transaction.py", line 217, in __exit__
    self.exiting(exc_value, self.using)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/transaction.py", line 286, in exiting
    leave_transaction_management(using=using)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/transaction.py", line 66, in leave_transaction_management
    connection.leave_transaction_management()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/backends/__init__.py", line 136, in leave_transaction_management
    self.rollback()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/backends/__init__.py", line 249, in rollback
    self._rollback()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/backends/mysql/base.py", line 421, in _rollback
    BaseDatabaseWrapper._rollback(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/django-1.5/django/db/backends/__init__.py", line 59, in _rollback
    return self.connection.rollback()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/storage/speckle/python/api/rdbms.py", line 890, in rollback
    self.MakeRequest('ExecOp', request)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/storage/speckle/python/api/rdbms.py", line 941, in MakeRequest
    response = self._MakeRetriableRequest(stub_method, request)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/storage/speckle/python/api/rdbms.py", line 970, in _MakeRetriableRequest
    raise _ToDbApiException(sql_exception)
InternalError: (0, u'Connection is already in use.')
```

**Comment by aisapatino** [comment]
Have yet to see this again; archiving
