### ISSUE TITLE
Server error accessing draft with non-ascii in filenames

### ISSUE THREAD

**Issue by aisapatino** [aisapatino/sjfnw#788]
```
URL:	https://sjf-nw.appspot.com/apply/28
Stacktrace:	
Traceback (most recent call last):
  File "/base/data/home/apps/s~sjf-nw/1.387057404700037190/libs/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~sjf-nw/1.387057404700037190/libs/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/base/data/home/apps/s~sjf-nw/1.387057404700037190/sjfnw/grants/decorators.py", line 32, in _wrapped_view
    return view_func(request, organization, *args, **kwargs)
  File "/base/data/home/apps/s~sjf-nw/1.387057404700037190/sjfnw/grants/views.py", line 332, in grant_application
    file_urls[field] = link_template.format(url, name, field)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 3: ordinal not in range(128)
```

Should be able to handle unicode, non-ascii chars.

**Comment by aisapatino** [comment]
Update [this line](https://github.com/aisapatino/sjfnw/blob/master/sjfnw/grants/views.py#L327) to make it a unicode string, then test
